apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: translation
    tier: backend
  name: translation-backend
---
apiVersion: v1
kind: Secret
metadata:
  name: translation-db-creds
  namespace: translation-backend
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: RGRBOXMxa3hIbTY1dnc4aQ==
  db-name: dHJhbnNsYXRpb24=
  host: MzQuMTMxLjI1NC4xNzk=
  port: NTQzMg==
---
apiVersion: v1
data:
  secret-key: Q1EhIkdObEdpLg==
  x-api-key: NDNiZDZjODljYTAwYjZkMDAwNDA1ZjVlODBhMjhmOTI1MjUwMWE3NjE3Mzg3ZDdmNzQwYTNjMjllZTQyZWZmNg==
  superuser-username: c3VwZXJhZG1pbg==
  supeuser-password: SjsjRiY/PStcaFdnYi52NW4hXDY4e1JBPlVCODs0
kind: Secret
metadata:
  name: saral-translation-secret
  namespace: translation-backend
type: Opaque

---
apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: translation-staging
 name: translation-staging
 namespace: translation-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: translation-staging
  template:
    metadata:
      labels:
        app: translation-staging
    spec:
      containers:
        - image: gcr.io/bjp-saral/github.com/jarvisconsulting/saral-translation
          imagePullPolicy: IfNotPresent
          name: translation-staging-deployment
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
          env:
            - name: X_API_KEY
              valueFrom:
                secretKeyRef:
                  name: saral-translation-secret
                  key: x-api-key
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: saral-translation-secret
                  key: secret-key
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: translation-db-creds
                  key: db-name
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: translation-db-creds
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: translation-db-creds
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: translation-db-creds
                  key: password
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: translation-db-creds
                  key: port
            - name: SUPERUSER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: saral-translation-secret
                  key: superuser-username
            - name: SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: saral-translation-secret
                  key: supeuser-password


---

apiVersion: v1
kind: Service
metadata:
  label:
    app: translation-staging
  name: translation-staging-service
  namespace: translation-backend
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: translation-staging
  sessionAffinity: None
  type: LoadBalancer
